- hosts: k3s_first,k3s_other,k3s_workers
  tasks:
    - name: Dist upgrade
      apt:
        upgrade: dist
    - name: Install curl
      apt:
        pkg: 
        - curl

- hosts: k3s_first
  tasks:
    - name: Install k3s on the first node
      ansible.builtin.shell: "curl -sfL https://get.k3s.io | K3S_TOKEN=someDankK3SToken sh -s - server --cluster-init"

- hosts: k3s_other
  tasks:
    - name: Install k3s on the other nodes
      ansible.builtin.shell: "curl -sfL https://get.k3s.io | K3S_TOKEN=someDankK3SToken sh -s - server --server https://192.168.1.130:6443"

- hosts: k3s_workers
  tasks:
    - name: Install k3s on the workers nodes
      ansible.builtin.shell: "curl -sfL https://get.k3s.io | K3S_URL=https://192.168.1.130:6443 K3S_TOKEN=someDankK3SToken sh -"

- hosts: localhost
  tasks:
    - name: Apt upgrade
      become: true
      apt:
        upgrade: full
    - name: Install required packages
      become: true
      apt:
        pkg: 
        - apt-transport-https 
        - ca-certificates
        - curl
    - name: Get signed key
      ansible.builtin.command: 'sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    - name: Add k8s repo's 
      ansible.builtin.command: 'echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list'
    - name: Apt upgrade
      become: true
      apt:
        upgrade: full
    - name: Install required packages
      become: true
      apt:
        pkg: 
        - kubectl
    - name: Copy authorized_keys to root user
      ansible.builtin.command: 'rsync root@192.168.1.130:/etc/rancher/k3s/k3s.yaml ~/.kube/config'