#!/bin/sh
### BEGIN INIT INFO
# Provides:          prerequisite kubernetes
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: prerequisite kubernetes
### END INIT INFO


case "${1}" in
   "start")
      ln -s /dev/console /dev/kmsg
      mount --make-rshared /
      ;;

   "stop")
      rm /dev/kmsg
      ;;
   *)
      echo "Usage: ${0} {start|stop}"
      exit 1
      ;;
esac